title: <p align="center"> Manoj Bisht </p>
logo: img/pic.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/manoj-bisht-b293a657/">LinkedIn</a> |
  <a href="https://github.com/manojbisht1990">GitHub</a>
  <br>   
  An Senior Front end Technical Lead with 9 years of experience. HTML/CSS, REACT, Python, SQL, Machine learning, javascript etc.
  <br>
  </p>



theme: jekyll-theme-minimal