title: <p align="center"> Manoj Bisht </p>
logo: img/pic.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/manoj-bisht-b293a657/">LinkedIn</a> |
  <a href="https://github.com/manojbisht1990">GitHub</a>
  
  <br>   
An Enthusiastic Front end Technical Lead with 8 years of experience. Excited about developing forward-thinking solutions to tomorrow's productivity problems. Resourceful and adaptable approach to challenges.Always an eye for clean and modular code

Good hands on experience with Frontend Frameworks,languages and libraries like AMP, ReactJs, JavaScript, jQuery, HTML5, CSS,BootStrap to name a few.

Being an excellent team player and team manager, I have ample experience working in Agile Environment and strive to deliver quality code that is modular and scalable. The utmost priority is a user-friendly and responsive experience across different devices.

Always strive to deliver efficient and optimised systems with minimum load time and maximum SEO footprint.

Excited and open to working on new technologies as I have been flexible about the same in my prior work experience.
  <br>
  </p>



theme: jekyll-theme-minimal